#!/usr/bin/python3.7

input="%63%70%61%73%62%69%65%6e%64%75%72%70%61%73%73%77%6f%72%64"
splitted=str.split(input,"%")
splitted.remove('')
result=""
for ch in splitted:
    result=result+chr(int(ch,16))
print(result)
